Fixed fall-through for PR #15315
/opt/civet/build_0/moose/framework/src/utils/SlepcSupport.C:385:40: error: this statement may fall through [-Werror=implicit-fallthrough=]
  385 |       solver_params._eigen_matrix_free = true;
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/opt/civet/build_0/moose/framework/src/utils/SlepcSupport.C:387:5: note: here
  387 |     case Moose::EST_NEWTON:
      |     ^~~~
cc1plus: all warnings being treated as errors

We changed APIs in  #15315, and we need to reserve the old APIs for Griffin for a second.

I will go to update Griffin to use new APIs. Once that is done, we could remove the old APIs.

Refs #15315