Fix mtwist warning in new version of clang.
This shows up because we treat warnings as errors with -Werror:
error: 'register' storage class specifier is deprecated and incompatible with C++17 [-Werror,-Wdeprecated-register]

I don't think the 'register' keyword in this file actually does
anything, so we should be able to remove them without any issues...

Refs #1777.