This test has to use SerialMesh because stitch_meshes() is only implemented for SerialMesh.
Note that running:

../../../moose_test-opt -i tiled_mesh_test.i --mesh-only --parallel-mesh

Produces the error:

 Exiting without writing output
 ERROR: Unrecognized file extension: --parallel-mesh

So I think there's something wrong with our command line argument processing...

Refs #2105.
Refs #2124.

r20838